import SwiftUI

/// Coach insight bubble from "Ola". Generated by `CoachService` (rule-
/// based today, LLM-backed once the Worker ships Claude). The view stays
/// dumb — colour + icon are derived from `insight.tone`.
struct AIInsightCard: View {
    let insight: CoachInsight
    var onAction: ((CoachInsight.ActionKind) -> Void)?
    var onDismiss: (() -> Void)?

    var body: some View {
        HStack(alignment: .top, spacing: 12) {
            MonoIconBox(systemName: iconName, style: .dark, size: 40)
            VStack(alignment: .leading, spacing: 4) {
                MonoLabel(text: "Ola")
                Text(insight.headline)
                    .font(Tokens.Font.manrope(16, weight: 800))
                    .foregroundStyle(Tokens.Palette.ink)
                    .fixedSize(horizontal: false, vertical: true)
                Text(insight.body)
                    .font(Tokens.Font.manrope(13, weight: 600))
                    .foregroundStyle(Tokens.Mono.muted)
                    .lineSpacing(2)
                    .fixedSize(horizontal: false, vertical: true)
                if let actionTitle = insight.actionTitle, let actionKind = insight.actionKind {
                    Button {
                        onAction?(actionKind)
                    } label: {
                        HStack(spacing: 4) {
                            Text(actionTitle)
                                .font(Tokens.Font.manrope(13, weight: 800))
                            Image(systemName: "chevron.right")
                                .font(.system(size: 11, weight: .bold))
                        }
                        .foregroundStyle(Tokens.Palette.ink)
                        .frame(height: 32)
                        .contentShape(Rectangle())
                    }
                    .buttonStyle(.plain)
                }
            }
            Spacer(minLength: 0)
        }
        .monoCard(padding: 16)
        .overlay(alignment: .topTrailing) {
            if insight.tone == .nudge || insight.tone == .celebration {
                Circle()
                    .fill(accent)
                    .frame(width: 8, height: 8)
                    .padding(14)
                    .accessibilityHidden(true)
            }
        }
        .contextMenu {
            if let onDismiss {
                Button {
                    onDismiss()
                } label: {
                    Label("Ukryj na dziś", systemImage: "eye.slash")
                }
            }
        }
    }

    private var iconName: String {
        switch insight.tone {
        case .encouragement: return "sparkles"
        case .suggestion: return "lightbulb.fill"
        case .nudge: return "bell.badge.fill"
        case .celebration: return "party.popper.fill"
        }
    }

    /// Tone dot colour (design D keeps the card neutral; tone shows as a small marker).
    private var accent: Color {
        switch insight.tone {
        case .encouragement, .suggestion: return Tokens.Mono.strong
        case .nudge: return Tokens.Mono.fat
        case .celebration: return Tokens.Mono.hi
        }
    }
}
