import Foundation

/// A single, render-ready piece of advice from "Ola". Generated by the
/// rule-based coach today, by the LLM coach once the Worker has Claude
/// wired. Both producers emit the same value type so views never branch.
struct CoachInsight: Equatable, Sendable, Identifiable {
    enum Tone: String, Sendable {
        /// Default warm tone — affirmations, gentle reminders.
        case encouragement
        /// Concrete dietary suggestion ("dorzuć białko").
        case suggestion
        /// Soft warning when a goal is at risk — never harsh.
        case nudge
        /// Celebration for a streak / weight / consistency milestone.
        case celebration
    }

    let id: UUID
    let tone: Tone
    let headline: String
    let body: String
    /// Optional CTA — e.g. "Add meal" linking to the scanner.
    let actionTitle: String?
    let actionKind: ActionKind?

    enum ActionKind: String, Sendable {
        case openScanner
        case openQuickDB
        case openRecipes
        case openWeightLog
    }

    init(
        id: UUID = UUID(),
        tone: Tone,
        headline: String,
        body: String,
        actionTitle: String? = nil,
        actionKind: ActionKind? = nil
    ) {
        self.id = id
        self.tone = tone
        self.headline = headline
        self.body = body
        self.actionTitle = actionTitle
        self.actionKind = actionKind
    }
}
