import SwiftUI

/// Coach insight bubble from "Ola". Generated by `CoachService` (rule-
/// based today, LLM-backed once the Worker ships Claude). The view stays
/// dumb — colour + icon are derived from `insight.tone`.
struct AIInsightCard: View {
    let insight: CoachInsight
    var onAction: ((CoachInsight.ActionKind) -> Void)?

    var body: some View {
        Card(background: background, elevation: Tokens.Shadow.card) {
            HStack(alignment: .top, spacing: Tokens.Space.md) {
                ZStack {
                    Circle()
                        .fill(accent)
                        .frame(width: 36, height: 36)
                    Image(systemName: iconName)
                        .font(.system(size: 16, weight: .semibold))
                        .foregroundStyle(.white)
                }
                VStack(alignment: .leading, spacing: 4) {
                    Text("Ola")
                        .font(Tokens.Font.footnote)
                        .foregroundStyle(accent)
                    Text(insight.headline)
                        .font(Tokens.Font.bodyEmphasized)
                        .foregroundStyle(Tokens.Palette.ink)
                    Text(insight.body)
                        .font(Tokens.Font.body)
                        .foregroundStyle(Tokens.Palette.ink)
                        .fixedSize(horizontal: false, vertical: true)
                    if let actionTitle = insight.actionTitle, let actionKind = insight.actionKind {
                        Button {
                            onAction?(actionKind)
                        } label: {
                            HStack(spacing: 4) {
                                Text(actionTitle)
                                    .font(Tokens.Font.footnote.bold())
                                Image(systemName: "arrow.right")
                                    .font(.system(size: 12, weight: .bold))
                            }
                            .foregroundStyle(accent)
                            .padding(.top, 2)
                        }
                        .buttonStyle(.plain)
                    }
                }
                Spacer(minLength: 0)
            }
        }
    }

    private var iconName: String {
        switch insight.tone {
        case .encouragement: return "sparkles"
        case .suggestion: return "lightbulb.fill"
        case .nudge: return "bell.badge.fill"
        case .celebration: return "party.popper.fill"
        }
    }

    private var accent: Color {
        switch insight.tone {
        case .encouragement, .suggestion: return Tokens.Palette.primary
        case .nudge: return Tokens.Palette.warning
        case .celebration: return Tokens.Palette.accent
        }
    }

    private var background: Color {
        switch insight.tone {
        case .nudge: return Tokens.Palette.warning.opacity(0.12)
        case .celebration: return Tokens.Palette.accent.opacity(0.12)
        default: return Tokens.Palette.primarySoft
        }
    }
}
